rule_files:
  - "/etc/prometheus/rules/*yml"
  - "/etc/prometheus/rules/*yaml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "prometheus-api"
    metrics_path: /api-metrics
    static_configs:
      - targets: ["prometheus-api:5000"]